# Generated by Django 3.0.4 on 2020-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_img',
            field=models.ImageField(default=0, upload_to='courses'),
            preserve_default=False,
        ),
    ]
